# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - make clean
    - go mod tidy

builds:
- main: ./cmd/graph/main.go
  env:
    - CGO_ENABLED=0
  goos:
    - linux
    - windows
    - darwin
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    # trims path
    - -trimpath
  ldflags:
    # use commit date instead of current date as main.date
    # only needed if you actually use those things in your main package, otherwise can be ignored.
    - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }}

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"

changelog:
  use: github
  sort: asc

release:
  name_template: 'v{{ .Version }}'
  github:
    owner: Sergk
    name: tkn-graph

# signs the checksum file
# all files (including the sboms) are included in the checksum, so we don't need to sign each one if we don't want to
# https://goreleaser.com/customization/sign
signs:
- cmd: gpg
  artifacts: checksum
  output: true

# create a source tarball
# https://goreleaser.com/customization/source/
source:
  enabled: true

# creates SBOMs of all archives and the source tarball using syft
# https://goreleaser.com/customization/sbom
sboms:
- artifacts: archive
- id: source # Two different sbom configurations need two different IDs
  artifacts: source

announce:
  skip: true

# modelines, feel free to remove those if you don't want/use them:
# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
